version: '3.8'

services:
  frontend:
    build:
      context: ./chatbot-widget
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./chatbot-widget:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./chatbot-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./chatbot-api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-dancechat_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 