name: Frontend CI

on:
  push:
    branches: [ main, development ]
    paths:
      - 'chatbot-widget/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'chatbot-widget/**'

# Limit permissions to minimum required
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chatbot-widget
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'
          cache-dependency-path: 'chatbot-widget/package-lock.json'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps || npm install --legacy-peer-deps

      - name: ESLint
        run: npm run lint
        continue-on-error: true  # Allow warnings for now
      
      - name: TypeScript Check
        run: npm run typecheck

      - name: Run Tests
        run: npm test -- --watchAll=false
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true 