name: Frontend CI

on:
  push:
    branches: [ main, development ]
    paths:
      - 'chatbot-widget/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'chatbot-widget/**'

jobs:
  frontend-ci:
    name: Lint, Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chatbot-widget

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Explicitly caching node_modules instead of using built-in npm cache
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: chatbot-widget/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('chatbot-widget/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint

      - name: TypeScript Check
        run: npm run typecheck

      - name: Run Tests
        run: npm test -- --watchAll=false --coverage
        env:
          CI: true

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info 